### ISSUE TITLE
Performance on WIDER FACE val 

### ISSUE THREAD

**Issue by YaqiLYU** [sfzhang15/FaceBoxes#1]
Can you provide the performance of FaceBoxes on WIDERFACE val?

**Comment by sfzhang15** [comment]
@YaqiLYU 
Hi, since we ignore the tiny faces during training and focus on the faces >=20pixels to reach the CPU real-time speed. While WIDER FACE has lots of tiny faces <20 pixels, so the performance may be unsatisfactory. If you want to know the performance, you can test our pretrained model by yourself.
