### ISSUE TITLE
Understanding shapes on Figure 1

### ISSUE THREAD

**Issue by mrgloom** [sfzhang15/FaceBoxes#32]
<img width="935" alt="Screenshot 2019-03-13 at 22 14 55" src="https://user-images.githubusercontent.com/4003908/54307761-784e5800-45dd-11e9-86fc-501825b9bcc0.png">

Can anyone comment on vertical lines with numbers:
```
3x3(2+4)x21
3x3(2+4)x1
3x3(2+4)x1
```

**Comment by zisianw** [comment]
3x3 refers to 3x3 conv. 2 for classification, 4 for anchor box regression, 21 for number of anchors.

**Comment by mrgloom** [comment]
So we have 21+1+1 anchors in total? How to calculate of number of bboxes from number of anchors? i.e. in paper they report `8,525boxes for a VGA-resolution image`. Also does the number of bboxes depends on image input size?

**Comment by mrgloom** [comment]
Looks like in this implementation:
https://github.com/TropComplique/FaceBoxes-tensorflow/blob/545ec4f4f3c55c3592ee189ed56a11a3fd017194/src/detector.py#L240

They have 2 separate convolutions for `box_encoding_predictor` and for `class_predictor`
https://github.com/TropComplique/FaceBoxes-tensorflow/blob/545ec4f4f3c55c3592ee189ed56a11a3fd017194/src/detector.py#L262
https://github.com/TropComplique/FaceBoxes-tensorflow/blob/545ec4f4f3c55c3592ee189ed56a11a3fd017194/src/detector.py#L276

**Comment by sfzhang15** [comment]
@mrgloom 
1. Each location of the detection layer is associated with some anchors, i.e., Inception3->21, Conv2_2->1, Conv4_2->1. Each location of Inception3 has 21 anchors = 16 of 32x32 anchor + 4 of 64x64 anchor + 1 of 128x128 anchor. The 32x32 anchor is densified 4 times to get 16 anchors and the 64x64 anchor is densified 2 times to get 4 anchors.
2. The number of bboxes depends on image input size, since the input image is larger, the feature map is larger too, resulting in more anchors.
