### ISSUE TITLE
1378:17: Message type "caffe.LayerParameter" has no field named "permute_param"

### ISSUE THREAD

**Issue by kk52099** [sfzhang15/FaceBoxes#45]
when I test the afw data, the error happed!  but when i trained the faceboxes ,it didnot happen

**Comment by sfzhang15** [comment]
@kk52099 
You can try to add 'sys.path.insert(0,'../python')' at the begin of afw_test.py.

**Comment by renatocastro33** [comment]
You have to use the caffe model in this github definitely because it is very different with the caffe normal installation, and also export the folder path of Faceboxes/python in the PythonPath after you compile the Makefile.config , and also check out the Makefile.config to uncomment lines if the paths or elements are correct (for example your OpenCv version if it is 3, or your Python version is 3.5).
